name: Android CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
defaults:
  run:
    shell: bash
    working-directory: Client/Seen-0.5.3-Not-IM/Seen
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Grant execute permission for gradlew
      run: |
        chmod +x gradlew
        gradlew assembleDebug
      
    - uses: actions/upload-artifact@v2
      with:
        name: upload-apk
        path: app/build/outputs/apk/app-debug.apk
