name: Android-Build-1.0.4
on: workflow_dispatch
defaults:
  run:
    shell: bash
    working-directory: Client/Seen-1.0.4-IM/Seen
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Permission for gradlew
      run: sudo chmod +x gradlew
    - name: assembleDebug
      run: bash ./gradlew assembleDebug --stacktrace

    - uses: actions/upload-artifact@v2
      with:
        name: Seen-v1.0.4.apk
        path: Client/Seen-1.0.4-IM/Seen/app/build/outputs/apk/debug/app-debug.apk
