name: Android CI
on: workflow_dispatch
defaults:
  run:
    shell: bash
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Client/Seen-0.5.3-Not-IM/Seen
    steps:

    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Grant execute permission for gradlew
      run: ls
      run: sudo apt-get install tree
      run: tree
      run: cd /home/runner/work/Seen/Seen
      run: ls
      run: chmod +x gradlew
      run: gradlew assembleDebug
      
    - uses: actions/upload-artifact@v2
      with:
        name: upload-apk
        path: ./app/build/outputs/apk/app-debug.apk
