name: Android-Build-0.5.3
on: workflow_dispatch
defaults:
  run:
    shell: bash
    working-directory: Client/Seen-0.5.3-NoIM/Seen
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Permission for gradlew
      run: sudo chmod +x gradlew
    - name: assembleDebug
      run: bash ./gradlew assembleDebug --stacktrace
      
#     - name: install tree
#       run: sudo apt-get install tree
#     - name: tree
#       run: tree

    - uses: actions/upload-artifact@v2
      with:
        name: Seen-v0.5.3.apk
        path: Client/Seen-0.5.3-NoIM/Seen/app/build/outputs/apk/debug/app-debug.apk
